#ifndef APP_SYSTEM_APP_SAFETY_CONFIG_H
#define APP_SYSTEM_APP_SAFETY_CONFIG_H

/* Safety feature switches and thresholds. */
#ifndef APP_SAFETY_OVER_TEMP_ENABLE
#define APP_SAFETY_OVER_TEMP_ENABLE 1U
#endif

#ifndef APP_SAFETY_OVER_TEMP_LIMIT_C
#define APP_SAFETY_OVER_TEMP_LIMIT_C 44.0f
#endif

#ifndef APP_SAFETY_INVALID_TEMP_ENABLE
#define APP_SAFETY_INVALID_TEMP_ENABLE 1U
#endif

#ifndef APP_SAFETY_INVALID_TEMP_CONFIRM_MS
#define APP_SAFETY_INVALID_TEMP_CONFIRM_MS 100U
#endif

#define APP_SAFETY_INVALID_TEMP_CONFIRM_COUNT(period_ms) \
    ((APP_SAFETY_INVALID_TEMP_CONFIRM_MS + (period_ms) - 1U) / (period_ms))

#ifndef APP_SAFETY_OVER_PRESSURE_ENABLE
#define APP_SAFETY_OVER_PRESSURE_ENABLE 1U
#endif

#ifndef APP_SAFETY_OVER_PRESSURE_LIMIT_MMHG
#define APP_SAFETY_OVER_PRESSURE_LIMIT_MMHG 1300.0f
#endif

#ifndef APP_SAFETY_OVER_PRESSURE_CONFIRM_MS
#define APP_SAFETY_OVER_PRESSURE_CONFIRM_MS 100U
#endif

#define APP_SAFETY_OVER_PRESSURE_CONFIRM_COUNT(period_ms) \
    ((APP_SAFETY_OVER_PRESSURE_CONFIRM_MS + (period_ms) - 1U) / (period_ms))

#ifndef APP_SAFETY_HEAT_OTP_FAULT_ENABLE
#ifdef HEAT_OTP_FAULT_REPORT_ENABLE
#define APP_SAFETY_HEAT_OTP_FAULT_ENABLE HEAT_OTP_FAULT_REPORT_ENABLE
#else
#define APP_SAFETY_HEAT_OTP_FAULT_ENABLE 0U
#endif
#endif

#ifndef APP_SAFETY_EYE_SHIELD_FUSE_PROTECTION_ENABLE
#ifdef EYE_SHIELD_IGNORE_FUSE_PROTECTION_DEBUG
#define APP_SAFETY_EYE_SHIELD_FUSE_PROTECTION_ENABLE \
    ((EYE_SHIELD_IGNORE_FUSE_PROTECTION_DEBUG) ? 0U : 1U)
#else
#define APP_SAFETY_EYE_SHIELD_FUSE_PROTECTION_ENABLE 0U
#endif
#endif

#ifndef APP_SAFETY_FUSE_BLOW_PULSE_MS
#ifdef EYE_SHIELD_FUSE_BLOW_PULSE_MS
#define APP_SAFETY_FUSE_BLOW_PULSE_MS EYE_SHIELD_FUSE_BLOW_PULSE_MS
#else
#define APP_SAFETY_FUSE_BLOW_PULSE_MS 10U
#endif
#endif

/* Compatibility aliases used by existing modules. */
#ifndef HEAT_OTP_FAULT_REPORT_ENABLE
#define HEAT_OTP_FAULT_REPORT_ENABLE APP_SAFETY_HEAT_OTP_FAULT_ENABLE
#endif

#ifndef EYE_SHIELD_IGNORE_FUSE_PROTECTION_DEBUG
#define EYE_SHIELD_IGNORE_FUSE_PROTECTION_DEBUG \
    ((APP_SAFETY_EYE_SHIELD_FUSE_PROTECTION_ENABLE) ? 0U : 1U)
#endif

#ifndef EYE_SHIELD_FUSE_BLOW_PULSE_MS
#define EYE_SHIELD_FUSE_BLOW_PULSE_MS APP_SAFETY_FUSE_BLOW_PULSE_MS
#endif

#endif
